apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-tst
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/rbel-io/helm-charts'
      targetRevision: HEAD
      path: charts/grafana
      helm:
        valueFiles:
        - $values/grafana/tst/values.yaml
    - repoURL: 'https://github.com/rbel-io/helm-values.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana-tst
  syncPolicy:
    automated:
      prune: true
